### ISSUE TITLE
mesos-docker-executor: error while loading shared libraries: libssl.so.1.0.0

### ISSUE THREAD

**Issue by smitchell** [dcos-labs/dcos-gce#19]
We've been using this project successfully for about four months now. This weekend I had to rebuild our cluster, following the same procedure we've been using. For some reason, Jenkins gets the error below, and OpenVPN won't deploy at all. I am still able to deploy MarathonLB.

mesos-docker-executor: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Is anybody else having problems with Google Cloud Platform? I thought maybe it was because I was using the latest CentOS build, but when I rolled back to /centos-cloud/centos-7-v20161129 I still had the same problem.

**Comment by ajazam** [comment]
I think this has been resolved in the mailing list. Can I close this issue?
