### ISSUE TITLE
Installation failed if bootstrap machine install Docker 1.12

### ISSUE THREAD

**Issue by kkdai** [dcos-labs/dcos-gce#2]
Only happen if bootstrap machine install latest Docker 1.12 

> TASK [start docker] ************************************************************
> fatal: [evan-dcos-master]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.\n"}
>   to retry, use: --limit @install.retry

**Comment by ajazam** [comment]
Fixed in 4e27607. Please see the change for modifying docker.service in the README.md
