### ISSUE TITLE
ansible-playbook -i hosts install.yml failed

### ISSUE THREAD

**Issue by easontsai** [dcos-labs/dcos-gce#29]
Hi all,
I'm new for dcos on GCP,below are some errors I saw.

I followed the Readme step by step to create the dcos.
some steps which need to be replaced and my setting are:
1.ssh-keygen -t rsa -f ~/.ssh/id_rsa -C dcos18 and prefix the dcos18.(Here I don't figure out what is my "username" )
2.create a .ansible.cfg file in the root.
3.the IP in the file ./hosts I set 10.140.0.3(my zone asia-east1,and bootstarp IP:10.140.0.2) .

I would appreciate for your help.

TASK [remove masters from known_hosts file] ***********************
```
failed: [localhost] (item=master0) => {"changed": true, "cmd": ["/
usr/bin/ssh-keygen", "-R", "master0"], "delta": "0:00:00.008467", 
"end": "2018-12-26 19:57:33.291838", "item": "master0", "msg": "no
n-zero return code", "rc": 255, "start": "2018-12-26 19:57:33.2833
71", "stderr": "do_known_hosts: hostkeys_foreach failed: No such f
ile or directory", "stderr_lines": ["do_known_hosts: hostkeys_fore
ach failed: No such file or directory"], "stdout": "", "stdout_lin
es": []}
...ignoring
```

TASK [remove  masters IP from known_hosts file] ******************

```
failed: [localhost] (item=master0) => {"changed": true, "cmd": ["/
usr/bin/ssh-keygen", "-R", "10.140.0.3"], "delta": "0:00:00.006626
", "end": "2018-12-26 19:57:33.553798", "item": "master0", "msg": 
"non-zero return code", "rc": 255, "start": "2018-12-26 19:57:33.5
47172", "stderr": "do_known_hosts: hostkeys_foreach failed: No suc
h file or directory", "stderr_lines": ["do_known_hosts: hostkeys_f
oreach failed: No such file or directory"], "stdout": "", "stdout_
lines": []}
...ignoring
```

TASK [wait for master instance creation to complete] *************
**************
FAILED - RETRYING: wait for master instance creation to complete (
300 retries left).
failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item
_result': True, '_ansible_item_label': u'master0', u'ansible_job_i
d': u'568314799743.4865', 'failed': False, u'started': 1, 'changed
': True, 'item': u'master0', u'finished': 0, u'results_file': u'/r
oot/.ansible_async/568314799743.4865', '_ansible_ignore_errors': N
one, '_ansible_no_log': False}) => {"ansible_job_id": "56831479974
3.4865", "attempts": 2, "changed": true, "cmd": ["/usr/bin/gcloud"
, "compute", "--project", "dcos18", "instances", "create", "master
0", "--zone", "asia-east1-a", "--machine-type", "n1-standard-1", "
--subnet", "default", "--private-network-ip", "10.140.0.3", "--mai
ntenance-policy", "MIGRATE", "--tags", "master", "--scopes", "http
s://www.googleapis.com/auth/cloud-platform", "--image", "centos-7-
v20161027", "--image-project", "centos-cloud", "--boot-disk-size",
 "10", "--boot-disk-type", "pd-standard", "--boot-disk-device-name
", "master0-boot", "--metadata", "hostname=master0"], "delta": "0:
00:01.562617", "end": "2018-12-26 19:57:35.421858", "finished": 1,
 "item": {"ansible_job_id": "568314799743.4865", "changed": true, 
"failed": false, "finished": 0, "item": "master0", "results_file":
 "/root/.ansible_async/568314799743.4865", "started": 1}, "msg": "
non-zero return code", "rc": 1, "start": "2018-12-26 19:57:33.8592
41", "stderr": "WARNING: You have selected a disk size of under [2
00GB]. This may result in poor I/O performance. For more informati
on, see: https://developers.google.com/compute/docs/disks#performa
nce.\nERROR: (gcloud.compute.instances.create) Could not fetch res
ource:\n - The resource 'projects/dcos18/zones/asia-east1-a/instan
ces/master0' already exists", "stderr_lines": ["WARNING: You have 
selected a disk size of under [200GB].This may result in poor I/O
 performance. For more information, see: https://developers.google
.com/compute/docs/disks#performance.", "ERROR: (gcloud.compute.ins
tances.create) Could not fetch resource:", " - The resource 'proje
cts/dcos18/zones/asia-east1-a/instances/master0' already exists"],
 "stdout": "", "stdout_lines": []}

**Comment by ajazam** [comment]
Hello,

The installation method you are following is no longer supported. Please follow the latest instructions at https://docs.mesosphere.com/1.12/installing/evaluation/mesosphere-supported-methods/gcp/
