### ISSUE TITLE
Ansible script unable to create master instance - permission related

### ISSUE THREAD

**Issue by sunnyyip** [dcos-labs/dcos-gce#3]
GCE returned error when create and configure master nodes with the ansible script. Likely a GCE config issue but the doc didn't specify the required permission.

ansible-playbook -i hosts install.yml

ERROR: (gcloud.compute.instance.create) Some request did not succeed:
- Required 'compute.subnetworks.use' permission for 'project/trek-trackr/regions/[region]/subnetworks/default'

**Comment by ajazam** [comment]
@sunnyyip You need to make the appropriate changes to groups_vars/all file. The fields you need to update for you project are project, subnet, login_name, bootstrap_public_ip & zone. To clear the above error you need to change the project name to your own project. You are using the default project name "trek-trackr"

**Comment by sunnyyip** [comment]
That's right....rookies mistake! In my case, I have project name intentionally left as "trek-trackr" but what the script wants is really the Project ID. Thanks!

**Comment by zirho** [comment]
Hi, I'm having the same issue. 

GCE-DCOS docs feels outdated.

![image](https://user-images.githubusercontent.com/1251296/27167755-49a738cc-5157-11e7-9b8f-8ea8cda1750a.png)

**Comment by ajazam** [comment]
The default project name is trek-trackr not trek-treckr
