### ISSUE TITLE
Unable to create agent nodes using the Ansible script

### ISSUE THREAD

**Issue by sunnyyip** [dcos-labs/dcos-gce#4]
New instance was created successfully but the script stopped at the error below:

(excerpt from ansible output)
[user@bootstrap dcos-gce]$ ansible-playbook -i hosts add_agents.yml
... 
things ran fine until
...
PLAY [start dcos bootstrap container] ******************************************

TASK [ensure dcos installer container is started] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error retrieving container list: ('Connection aborted.', error(2, 'No such file or directory'))"}

**Comment by ajazam** [comment]
At a guess I would say docker isn't running.

Can you do following and tell me what you get?

``` bash
sudo docker run hello-world
```

**Comment by sunnyyip** [comment]
Thanks ajazam! You’re right. Docker wasn’t running on the bootstrap node when the script was run.

**Comment by ajazam** [comment]
There was a problem with my script. If you try to add an agent after teh bootstrap node is restarted then docker on the bootstrap node does not start. It's fixed now in bb1be959e436e238c0cfdb5a13a354ff89f01170
